debug: false
server:
  port: 8080 #tomcat运行端口
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(EGVln/0bmIejAwvTzDNw828GGHKo00I0UgwHofRMkGHJOxoHwOIleL+sJa1U6p2ynqQnvUxEqvE=)
    username: ENC(bj5AMYvG8zZ956TDzg/6FMaZo0YK2BXt)
    password: ENC(F4SHg+Y7jo2GC2BnKvx8Rs8b5biSGt60)
    druid:
      initial-size: 1
      max-active: 100
      min-idle: 1
      max-wait: 20000 # 配置获取连接等待超时的时间
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20 #和上面的等价
      # validation-query: SELECT 'x'
      validation-query: SELECT 'x' FROM DUAL
      validation-query-timeout: 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      filters: stat

  redis:
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
    database: 0
    # redis服务器地址（默认为localhost）
    host: 19.104.50.204
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password: ENC(18y0O78BQc5x3eqduciALjZjw5P80+Y4)
    # redis连接超时时间（单位为毫秒）
    timeout: 10000
    # redis连接池配置
    jedis:
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: 500
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 8
        # 最小空闲连接数（默认为0，该值只有为正数才有作用）
        min-idle: 0
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: 5000

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  activiti:
    check-process-definitions: false
    database-schema-update: true

ljdp:
  ftpserver:
    url: 19.104.50.204
    port: 21
    mode: PASV
    username: nanjian
    password: ENC(GnxvP/7gqmPanTdk56XI0L4E7lt7w5FOcQawRI5b0S8=)
    remote-path: /
    local-temp-path: /tmp
  dfs:
    ftp2http-proxy: http://19.104.50.204/iocadminsvc/ftp
    ftp2http-download: http://19.104.50.204/iocadminsvc/ljdp/dfs/downloadByFid.act?fid=
  fileupload:
    # 覆盖batch.fileupload.path配置
    local-path: /tmp
  security:
    api:
      skey: ENC(U9gx2By8DaCRK/VM7SgZfFluZy8G7InNSmJvTnI8LEDxL8GSns8dVWZJ0cHm6mY2)

custom:
  kong:
    admin-api: http://kong-admin.kong-api:8001
    proxy-http: http://19.104.50.204
    proxy-https: https://19.104.50.204
  paas:
    url: http://platform-svr-app.ioc-paas-platform:9101
    username: iocadmin
    password: iocadmin
    namespace: ioc-paas-platform
  schedule: false
  auth-url: http://ioc-admin-svc.ioc-platform:8080
  #service-id: 801490971320024

kylin:
  address:  http://19.104.59.1:7070
  account:  ADMIN
  pwd:  KYLIN
  authorization:  Basic QURNSU46S1lMSU4=
olap:
  sync:
    realTableNamePrefix: OLAP_
  kylin:
    databaseName: olap
  datalake:
    #调用数据集模块的接口地址
    host: http://ioc-dataset-svc.ioc-platform.svc:8080
    querySyncJobStateUrl: /pds/datasync/dataSync/batchStatus
    batchCreateSyncJobUrl: /pds/datasync/dataSync/batchCreateJob
    batchActiveSyncJobUrl: /pds/datasync/dataSync/batchTriggerJob

gateway:
  address:  http://ioc-paas-svc.ioc-platform.svc:8080
