# 多环境配置文件激活属性
spring:
  profiles:
      active: dev
  # 缓存配置
#  cache:
#    type: ehcache
#    ehcache:
#      config: classpath:ehcache.xml
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.openjava.**.domain
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: INPUT
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: true
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

jasypt:
  encryptor:
    password: Lt4U6EgL19D2k_HY-AcD7-VAmq1OeLGqDdTTayXtH88

iocplatform:
  url:
    ioc-admin: http://ioc-admin-svc:8080
    # 跨局的附件下载的网关地址
    file-download-gateway:
      # 这里的url要用外网的地址，不能用服务名的方式
      url: https://19.104.50.204
      #通过附件下载的网关地址来下载附件：{0}需要下载的某局附件的局编码、{1}需要下载的附件id
      download-path: ${iocplatform.url.file-download-gateway.url}/dmp/{0}/datatransferweb/admin/dfs/objectcatalog/download?objectkey={1}
      minio-download-path: ${iocplatform.url.file-download-gateway.url}/dmp/{0}/datalakeweb/{1}