const getters = {
  sidebar: state => state.app.sidebar,
  device: state => state.app.device,
  token: state => state.user.token,
  userInfo: state => state.user.userInfo,
  menuList: state => state.app.menuList,
  treeList: state => state.olap.treeList,
  serchTableList: state => state.olap.serchTableList,
  saveSelectTable: state => state.olap.saveSelectTable,
  saveLocalSelectTable: state => state.olap.saveLocalSelectTable,
  selectTableTotal: state => state.olap.selectTableTotal,
  lastClickTab: state => state.olap.lastClickTab,
  saveSelctchckoutone: state => state.olap.saveSelctchckoutone,
  saveSelctchckouttwo: state => state.olap.saveSelctchckouttwo,
  saveSelectFiled: state => state.olap.saveSelectFiled,
  saveSelectFiledTree: state => state.olap.saveSelectFiledTree,
  saveNewSortList: state => state.olap.saveNewSortList,
  saveList: state => state.olap.saveList,
  saveRightTableList: state => state.olap.saveRightTableList,
  measureTableList: state => state.olap.measureTableList,
  relaodFilterList: state => state.olap.relaodFilterList,
  savedimensionData: state => state.olap.savedimensionData,
  savehetComposeData: state => state.olap.savehetComposeData,
  totalSaveList: state => state.olap.totalSaveList
}
export default getters
