package com.openjava.olap.common;

public enum AuditLogEnum {

    LOG_SERVICE_NAME("BI分析报表"),

    LOG_MODULES_OLAP_MODEL("OLAP模型"),
    LOG_MODULES_REAL_TIME_QUERY("即席查询"),
    LOG_MODULES_ANALYZE("OLAP分析"),

    LOG_OLAP_MODEL_TITLE_LEVEL_PRIMARY_MODEL_LIST("模型列表"),
    LOG_OLAP_MODEL_TITLE_LEVEL_PRIMARY_SHARE_LIST("共享列表"),
    LOG_OLAP_MODEL_TITLE_LEVEL_PRIMARY_BUILD_LIST("构建列表"),
    LOG_REAL_TIME_QUERY_TITLE_LEVEL_PRIMARY_SAVE_QUERY("新建查询"),
    LOG_REAL_TIME_QUERY_TITLE_LEVEL_PRIMARY_SAVED_RESULT("已保存结果"),
    LOG_REAL_TIME_QUERY_TITLE_LEVEL_PRIMARY_SHARE_RESULT("共享结果"),
    LOG_ANALYZE_TITLE_LEVEL_PRIMARY_MINE("我的"),
    LOG_ANALYZE_TITLE_LEVEL_PRIMARY_SHARE("共享"),


    LOG_OLAP_MODEL_TITLE_LEVEL_SECONDARY_MODEL_LIST_SAVE("新增"),
    LOG_OLAP_MODEL_TITLE_LEVEL_SECONDARY_MODEL_LIST_VIEW("查看"),
    LOG_OLAP_MODEL_TITLE_LEVEL_SECONDARY_MODEL_LIST_EDIT("编辑"),
    LOG_OLAP_MODEL_TITLE_LEVEL_SECONDARY_MODEL_LIST_BUILD("构建"),
    LOG_OLAP_MODEL_TITLE_LEVEL_SECONDARY_MODEL_LIST_REFRESH("刷新"),
    LOG_OLAP_MODEL_TITLE_LEVEL_SECONDARY_MODEL_LIST_SHARE("分享"),
    LOG_OLAP_MODEL_TITLE_LEVEL_SECONDARY_MODEL_LIST_ENABLE("启用"),
    LOG_OLAP_MODEL_TITLE_LEVEL_SECONDARY_MODEL_LIST_DISABLE("禁用"),
    LOG_OLAP_MODEL_TITLE_LEVEL_SECONDARY_MODEL_LIST_DELETE("删除"),

    LOG_OLAP_MODEL_TITLE_LEVEL_SECONDARY_SHARE_LIST_VIEW("查看"),
    LOG_OLAP_MODEL_TITLE_LEVEL_SECONDARY_SHARE_LIST_DELETE("删除"),

    LOG_OLAP_MODEL_TITLE_LEVEL_SECONDARY_BUILD_LIST_CHECK_LOG("查看日志"),
    LOG_OLAP_MODEL_TITLE_LEVEL_SECONDARY_BUILD_LIST_DELETE("删除"),


    LOG_REAL_TIME_QUERY_TITLE_LEVEL_SECONDARY_SAVE_QUERY_QUERY("查询"),
    LOG_REAL_TIME_QUERY_TITLE_LEVEL_SECONDARY_SAVE_QUERY_PERSIST_RESULT("保存结果"),
    LOG_REAL_TIME_QUERY_TITLE_LEVEL_SECONDARY_SAVE_QUERY_EXPORT_RESULT("导出结果"),


    LOG_REAL_TIME_QUERY_TITLE_LEVEL_SECONDARY_SAVED_RESULT_PERSIST_FOLDER("新建文件夹"),
    LOG_REAL_TIME_QUERY_TITLE_LEVEL_SECONDARY_SAVED_RESULT_EDIT_FOLDER("编辑文件夹"),
    LOG_REAL_TIME_QUERY_TITLE_LEVEL_SECONDARY_SAVED_RESULT_DELETE_FOLDER("删除文件夹"),
    LOG_REAL_TIME_QUERY_TITLE_LEVEL_SECONDARY_SAVED_RESULT_QUERY_DATA("查询数据"),
    LOG_REAL_TIME_QUERY_TITLE_LEVEL_SECONDARY_SAVED_RESULT_EDIT("编辑"),
    LOG_REAL_TIME_QUERY_TITLE_LEVEL_SECONDARY_SAVED_RESULT_EXPORT_RESULT("导出结果"),
    LOG_REAL_TIME_QUERY_TITLE_LEVEL_SECONDARY_SAVED_RESULT_PUBLISH("发布接口"),
    LOG_REAL_TIME_QUERY_TITLE_LEVEL_SECONDARY_SAVED_RESULT_SHARING("共享"),

    LOG_REAL_TIME_QUERY_TITLE_LEVEL_SECONDARY_SHARE_RESULT_EXPORT_RESULT("导出结果"),


    LOG_ANALYZE_TITLE_LEVEL_SECONDARY_MINE_PERSIST_FOLDER("新建文件夹"),
    LOG_ANALYZE_TITLE_LEVEL_SECONDARY_MINE_EDIT_FOLDER("编辑文件夹"),
    LOG_ANALYZE_TITLE_LEVEL_SECONDARY_MINE_DELETE_FOLDER("删除文件夹"),
    LOG_ANALYZE_TITLE_LEVEL_SECONDARY_MINE_NEW_REAL_TIME_ANALYZE("新建OLAP分析"),
    LOG_ANALYZE_TITLE_LEVEL_SECONDARY_MINE_EDIT("编辑"),
    LOG_ANALYZE_TITLE_LEVEL_SECONDARY_MINE_SHARING("共享"),
    LOG_ANALYZE_TITLE_LEVEL_SECONDARY_MINE_EXPORT("导出"),
    LOG_ANALYZE_TITLE_LEVEL_SECONDARY_MINE_PUBLISH("发布接口"),



    LOG_ANALYZE_TITLE_LEVEL_SECONDARY_SHARE_EXPORT("导出");



    AuditLogEnum(String value){
        this.value = value;
    }
    private String value;

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public enum AuditLogEvent{
        LOG_EVENT_MANAGE(1),
        LOG_EVENT_QUERY(2),
        LOG_EVENT_EXPORT(3),
        LOG_EVENT_LOAD(4);

        private Integer index;

        AuditLogEvent(Integer index) {
            this.index = index;
        }

        public Integer getIndex() {
            return index;
        }

        public void setIndex(Integer index) {
            this.index = index;
        }
    }
}
